In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('auto-mpg.csv')

In [6]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [7]:
print(df.head(10)) #Load the dataset into a Pandas DataFrame. Display: The first 10 rows The total number of rows and columns Summary statistics for numerical columns

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70
1  15.0          8         350.0        165    3693          11.5          70
2  18.0          8         318.0        150    3436          11.0          70
3  16.0          8         304.0        150    3433          12.0          70
4  17.0          8         302.0        140    3449          10.5          70
5  15.0          8         429.0        198    4341          10.0          70
6  14.0          8         454.0        220    4354           9.0          70
7  14.0          8         440.0        215    4312           8.5          70
8  14.0          8         455.0        225    4425          10.0          70
9  15.0          8         390.0        190    3850           8.5          70

   origin                   car name
0       1  chevrolet chevelle malibu
1       1          buick skylark 320
2       1         plymouth satellite
3       1              amc rebel sst
4       1                ford torino
5       1           ford galaxie 500
6       1           chevrolet impala
7       1          plymouth fury iii
8       1           pontiac catalina
9       1         amc ambassador dpl

In [8]:
print("Rows and Columns:", df.shape)

Rows and Columns: (398, 9)

In [9]:
print(df.describe())

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

In [12]:
df_filtered = print(df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]) #Find all cars manufactured in 1975 with a weight less than 3000. Return theDataFrame with selected columns: car_name, weight, and mpg

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [13]:
print(df.isnull().sum()) #Identify if there are any missing values in the dataset. Replace missing values in thehorsepower column with the column's media

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [14]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [19]:
median_hp = df['horsepower'].median()
df['horsepower'] = df['horsepower'].fillna(median_hp)

In [20]:
print(df['horsepower'].isnull().sum())

0

In [21]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight'] #Add a new column power_to_weight_ratio, calculated as horsepower / weight

In [22]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,0.040591

In [23]:
df.groupby('origin')['mpg'].mean() #Group the cars by origin and calculate the mean mpg for each group

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [24]:
mean_mpg_by_origin = print(df.groupby('origin')['mpg'].mean())

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [ ]:
top_10_mpg_cars = print(df.sort_values(by='mpg', ascending=False).head(10)) #Sort the DataFrame by mpg in descending order and display the top 10 cars withthe highest mpg Create a new column performance_score using a custom function:def performance_score(row):return row['mpg'] * row['acceleration'] / row['weight']

In [26]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

In [27]:
df['performance_score'] = df.apply(performance_score, axis=1) #Apply this function to each row and store the result in the new column

In [28]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio,performance_score
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,0.037100,0.061644
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,0.044679,0.046710
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,0.043655,0.057625
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,0.043694,0.055928
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,0.040591,0.051754

In [30]:
summary_df = print(df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()) #Generate a summary DataFrame with:Average mpg, weight, and horsepower for each model_year

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839